name: polkawallet_sdk
description: Flutter SDK for building plugin package for polkawallet.
version: 0.0.1
author: shawn@polkawallet.io
homepage: polkawallet.io

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  webview_flutter: ^1.0.7
  flutter_webview_plugin: ^0.3.11
  shared_preferences: ^0.5.6
  get_storage: ^1.3.0
  json_annotation: ^3.0.1
  flutter_aes_ecb_pkcs5: ^0.1.1
  convert: ^2.1.1
  mobx: ^1.2.1+2

dev_dependencies:
  mobx_codegen: ^1.1.0+2
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.0.0

dependency_overrides:
  analyzer: 0.39.15
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - js_api/dist/main.js
     - js_as_extension/dist/main.js
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
